version: '2'
services:
  server:
    image: postgrest/postgrest
    ports:
    - "3000:3000"
    environment:
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: web_anon
  swagger:
    image: swaggerapi/swagger-ui
    ports:
    - "8080:8080"
    expose:
    - "8080"
