CREATE TABLE publication
(
  id INTEGER PRIMARY KEY DEFAULT nextval('cpic_id'),
  guidelineid INTEGER REFERENCES guideline(id),
  title VARCHAR(200),
  authors TEXT[],
  journal varchar(200),
  month integer,
  page varchar(50),
  volume varchar(50),
  year integer,
  pmid text,
  pmcid text,
  doi text
);

\copy publication(title,guidelineid,authors,journal,month,page,volume,year,pmid) from STDIN;
Clinical Pharmacogenetics Implementation Consortium (CPIC) guidelines for IFNL3 (IL28B) genotype and peginterferon alpha based regimens	100000	{"Muir Andrew J","Gong Li","Johnson Samuel G","Michael Lee Ming Ta","Williams Marc S","Klein Teri E","Caudle Kelly E","Nelson David R"}	Clinical pharmacology and therapeutics	10	null	null	2013	24096968
Clinical Pharmacogenetics Implementation Consortium (CPIC) Guidelines for Ivacaftor Therapy in the Context of CFTR Genotype	100001	{"Clancy John P","Johnson Samuel G","Yee Sook Wah","McDonagh Ellen M","Caudle Kelly E","Klein Teri E","Cannavo Matthew","Giacomini Kathleen M"}	Clinical pharmacology and therapeutics	3	null	null	2014	24598717
Clinical pharmacogenetics implementation consortium guidelines for thiopurine methyltransferase genotype and thiopurine dosing	100002	{"Relling M V","Gardner E E","Sandborn W J","Schmiegelow K","Pui C-H","Yee S W","Stein C M","Carrillo M","Evans W E","Klein T E"}	Clinical pharmacology and therapeutics	3	387-91	89	2011	21270794
Clinical Pharmacogenetics Implementation Consortium Guidelines for Thiopurine Methyltransferase Genotype and Thiopurine Dosing: 2013 Update	100002	{"Relling M V","Gardner E E","Sandborn W J","Schmiegelow K","Pui C-H","Yee S W","Stein C M","Carrillo M","Evans W E","Hicks J K","Schwab M","Klein T E"}	Clinical pharmacology and therapeutics	1	null	null	2013	23422873
Clinical Pharmacogenetics Implementation Consortium (CPIC) Guidelines for Rasburicase Therapy in the context of G6PD Deficiency Genotype	100003	{"Relling Mary V","McDonagh Ellen M","Chang Tamara","Caudle Kelly E","McLeod Howard L","Haidar Cyrine E","Klein Teri","Luzzatto Lucio"}	Clinical pharmacology and therapeutics	5	null	null	2014	24787449
Clinical pharmacogenetics implementation consortium guidelines for thiopurine methyltransferase genotype and thiopurine dosing	100004	{"Relling M V","Gardner E E","Sandborn W J","Schmiegelow K","Pui C-H","Yee S W","Stein C M","Carrillo M","Evans W E","Klein T E"}	Clinical pharmacology and therapeutics	3	387-91	89	2011	21270794
Clinical Pharmacogenetics Implementation Consortium Guidelines for Thiopurine Methyltransferase Genotype and Thiopurine Dosing: 2013 Update	100004	{"Relling M V","Gardner E E","Sandborn W J","Schmiegelow K","Pui C-H","Yee S W","Stein C M","Carrillo M","Evans W E","Hicks J K","Schwab M","Klein T E"}	Clinical pharmacology and therapeutics	1	null	null	2013	23422873
Clinical Pharmacogenetics Implementation Consortium Guidelines for Cytochrome P450-2C19 (CYP2C19) Genotype and Clopidogrel Therapy	100005	{"Scott S A","Sangkuhl K","Gardner E E","Stein C M","Hulot J-S","Johnson J A","Roden D M","Klein T E","Shuldiner A R"}	Clinical pharmacology and therapeutics	6	null	null	2011	21716271
Clinical Pharmacogenetics Implementation Consortium (CPIC) guidelines for cytochrome P450-2C19 (CYP2C19) genotype and clopidogrel therapy: 2013 Update	100005	{"Scott Stuart A","Sangkuhl Katrin","Stein C Michael","Hulot Jean-Sébastien","Mega Jessica L","Roden Dan M","Klein Teri E","Sabatine Marc S","Johnson Julie A","Shuldiner Alan R"}	Clinical pharmacology and therapeutics	5	null	null	2013	23698643
Clinical Pharmacogenetics Implementation Consortium Guidelines for CYP2C9 and VKORC1 Genotypes and Warfarin Dosing	100006	{"Johnson J A","Gong L","Whirl-Carrillo M","Gage B F","Scott S A","Stein C M","Anderson J L","Kimmel S E","Lee M T M","Pirmohamed M","Wadelius M","Klein T E","Altman R B"}	Clinical pharmacology and therapeutics	9	null	null	2011	21900891
Clinical pharmacogenetics implementation consortium (cpic) guideline for pharmacogenetics-guided warfarin dosing: 2017 update	100006	{"Johnson Julie A","Caudle Kelly E","Gong Li","Whirl-Carrillo Michelle","Stein C Michael","Scott Stuart A","Lee Ming Ta Michael","Gage Brian F","Kimmel Stephen E","Perera Minoli A","Anderson Jeffrey L","Pirmohamed Munir","Klein Teri E","Limdi Nita A","Cavallari Larisa H","Wadelius Mia"}	Clinical pharmacology and therapeutics	2	null	null	2017	28198005
Clinical Pharmacogenetics Implementation Consortium (CPIC) Guidelines for CYP2C9 and HLA-B Genotype and Phenytoin Dosing	100007	{"Caudle Kelly E","Rettie Allan E","Whirl-Carrillo Michelle","Smith Lisa H","Mintzer Scott E","Lee Ming Ta Michael","Klein Teri E","Callaghan J Thomas"}	Clinical pharmacology and therapeutics	8	null	null	2014	25099164
Clinical pharmacogenetics implementation consortium guidelines for thiopurine methyltransferase genotype and thiopurine dosing	100008	{"Relling M V","Gardner E E","Sandborn W J","Schmiegelow K","Pui C-H","Yee S W","Stein C M","Carrillo M","Evans W E","Klein T E"}	Clinical pharmacology and therapeutics	3	387-91	89	2011	21270794
Clinical Pharmacogenetics Implementation Consortium Guidelines for Thiopurine Methyltransferase Genotype and Thiopurine Dosing: 2013 Update	100008	{"Relling M V","Gardner E E","Sandborn W J","Schmiegelow K","Pui C-H","Yee S W","Stein C M","Carrillo M","Evans W E","Hicks J K","Schwab M","Klein T E"}	Clinical pharmacology and therapeutics	1	null	null	2013	23422873
Clinical Pharmacogenetics Implementation Consortium (CPIC) Guidelines for Codeine Therapy in the Context of Cytochrome P450 2D6 (CYP2D6) Genotype	100009	{"Crews K R","Gaedigk A","Dunnenberger H M","Klein T E","Shen D D","Callaghan J T","Kharasch E D","Skaar T C"}	Clinical pharmacology and therapeutics	12	null	null	2011	22205192
Clinical Pharmacogenetics Implementation Consortium (CPIC) guidelines for cytochrome P450 2D6 (CYP2D6) genotype and codeine therapy: 2014 Update	100009	{"Crews Kristine R","Gaedigk Andrea","Dunnenberger Henry M","Leeder J Steve","Klein Teri E","Caudle Kelly E","Haidar Cyrine E","Shen Danny D","Callaghan John T","Sadhasivam Senthilkumar","Prows Cynthia A","Kharasch Evan D","Skaar Todd C"}	Clinical pharmacology and therapeutics	1	null	null	2014	24458010
Clinical Pharmacogenetics Implementation Consortium Guidelines for HLA-B Genotype and Abacavir Dosing	100010	{"Martin M A","Klein T E","Dong B J","Pirmohamed M","Haas D W","Kroetz D L"}	Clinical pharmacology and therapeutics	2	null	null	2012	22378157
Clinical Pharmacogenetics Implementation Consortium (CPIC) Guidelines for HLA-B Genotype and Abacavir Dosing: 2014 update	100010	{"Martin Michael A","Hoffman James M","Freimuth Robert R","Klein Teri E","Dong Betty J","Pirmohamed Munir","Hicks J Kevin","Wilkinson Mark R","Haas David W","Kroetz Deanna L"}	Clinical pharmacology and therapeutics	2	null	null	2014	24561393
Clinical Pharmacogenetics Implementation Consortium Guideline for CYP2D6 and CYP2C19 Genotypes and Dosing of Tricyclic Antidepressants	100011	{"Hicks J K","Swen J J","Thorn C F","Sangkuhl K","Kharasch E D","Ellingrod V L","Skaar T C","Müller D J","Gaedigk A","Stingl J C"}	Clinical pharmacology and therapeutics	1	null	null	2013	23486447
Clinical Pharmacogenetics Implementation Consortium Guideline (CPIC®) for CYP2D6 and CYP2C19 Genotypes and Dosing of Tricyclic Antidepressants: 2016 Update	100011	{"Kevin Hicks J","Sangkuhl Katrin","Swen Jesse J","Ellingrod Vicki L","Müller Daniel J","Shimoda Kazutaka","Bishop Jeffrey R","Kharasch Evan D","Skaar Todd C","Gaedigk Andrea","Dunnenberger Henry M","Klein Teri E","Caudle Kelly E","Stingl Julia C"}	Clinical pharmacology and therapeutics	12	null	null	2016	27997040
Clinical Pharmacogenetics Implementation Consortium Guideline for CYP2D6 and CYP2C19 Genotypes and Dosing of Tricyclic Antidepressants	100012	{"Hicks J K","Swen J J","Thorn C F","Sangkuhl K","Kharasch E D","Ellingrod V L","Skaar T C","Müller D J","Gaedigk A","Stingl J C"}	Clinical pharmacology and therapeutics	1	null	null	2013	23486447
Clinical Pharmacogenetics Implementation Consortium Guideline (CPIC®) for CYP2D6 and CYP2C19 Genotypes and Dosing of Tricyclic Antidepressants: 2016 Update	100012	{"Kevin Hicks J","Sangkuhl Katrin","Swen Jesse J","Ellingrod Vicki L","Müller Daniel J","Shimoda Kazutaka","Bishop Jeffrey R","Kharasch Evan D","Skaar Todd C","Gaedigk Andrea","Dunnenberger Henry M","Klein Teri E","Caudle Kelly E","Stingl Julia C"}	Clinical pharmacology and therapeutics	12	null	null	2016	27997040
Clinical Pharmacogenetics Implementation Consortium Guideline for CYP2D6 and CYP2C19 Genotypes and Dosing of Tricyclic Antidepressants	100013	{"Hicks J K","Swen J J","Thorn C F","Sangkuhl K","Kharasch E D","Ellingrod V L","Skaar T C","Müller D J","Gaedigk A","Stingl J C"}	Clinical pharmacology and therapeutics	1	null	null	2013	23486447
Clinical Pharmacogenetics Implementation Consortium Guideline (CPIC®) for CYP2D6 and CYP2C19 Genotypes and Dosing of Tricyclic Antidepressants: 2016 Update	100013	{"Kevin Hicks J","Sangkuhl Katrin","Swen Jesse J","Ellingrod Vicki L","Müller Daniel J","Shimoda Kazutaka","Bishop Jeffrey R","Kharasch Evan D","Skaar Todd C","Gaedigk Andrea","Dunnenberger Henry M","Klein Teri E","Caudle Kelly E","Stingl Julia C"}	Clinical pharmacology and therapeutics	12	null	null	2016	27997040
Clinical Pharmacogenetics Implementation Consortium Guideline for CYP2D6 and CYP2C19 Genotypes and Dosing of Tricyclic Antidepressants	100014	{"Hicks J K","Swen J J","Thorn C F","Sangkuhl K","Kharasch E D","Ellingrod V L","Skaar T C","Müller D J","Gaedigk A","Stingl J C"}	Clinical pharmacology and therapeutics	1	null	null	2013	23486447
Clinical Pharmacogenetics Implementation Consortium Guideline (CPIC®) for CYP2D6 and CYP2C19 Genotypes and Dosing of Tricyclic Antidepressants: 2016 Update	100014	{"Kevin Hicks J","Sangkuhl Katrin","Swen Jesse J","Ellingrod Vicki L","Müller Daniel J","Shimoda Kazutaka","Bishop Jeffrey R","Kharasch Evan D","Skaar Todd C","Gaedigk Andrea","Dunnenberger Henry M","Klein Teri E","Caudle Kelly E","Stingl Julia C"}	Clinical pharmacology and therapeutics	12	null	null	2016	27997040
Clinical Pharmacogenetics Implementation Consortium Guideline for CYP2D6 and CYP2C19 Genotypes and Dosing of Tricyclic Antidepressants	100015	{"Hicks J K","Swen J J","Thorn C F","Sangkuhl K","Kharasch E D","Ellingrod V L","Skaar T C","Müller D J","Gaedigk A","Stingl J C"}	Clinical pharmacology and therapeutics	1	null	null	2013	23486447
Clinical Pharmacogenetics Implementation Consortium Guideline (CPIC®) for CYP2D6 and CYP2C19 Genotypes and Dosing of Tricyclic Antidepressants: 2016 Update	100015	{"Kevin Hicks J","Sangkuhl Katrin","Swen Jesse J","Ellingrod Vicki L","Müller Daniel J","Shimoda Kazutaka","Bishop Jeffrey R","Kharasch Evan D","Skaar Todd C","Gaedigk Andrea","Dunnenberger Henry M","Klein Teri E","Caudle Kelly E","Stingl Julia C"}	Clinical pharmacology and therapeutics	12	null	null	2016	27997040
Clinical Pharmacogenetics Implementation Consortium Guidelines for Human Leukocyte Antigen-B Genotype and Allopurinol Dosing	100016	{"Hershfield M S","Callaghan J T","Tassaneeyakul W","Mushiroda T","Thorn C F","Klein T E","Lee M T M"}	Clinical pharmacology and therapeutics	10	null	null	2012	23232549
Clinical Pharmacogenetics Implementation Consortium (CPIC) guidelines for human leukocyte antigen B (HLA-B) genotype and allopurinol dosing: 2015 update	100016	{"Saito Y","Stamp L K","Caudle K E","Hershfield M S","McDonagh E M","Callaghan J T","Tassaneeyakul W","Mushiroda T","Kamatani N","Goldspiel B R","Phillips E J","Klein T E","Lee Mtm"}	Clinical pharmacology and therapeutics	6	null	null	2015	26094938
The Clinical Pharmacogenomics Implementation Consortium: CPIC Guideline for SLCO1B1 and Simvastatin-Induced Myopathy	100017	{"Wilke R A","Ramsey L B","Johnson S G","Maxwell W D","McLeod H L","Voora D","Krauss R M","Roden D M","Feng Q","Cooper-Dehoff R M","Gong L","Klein T E","Wadelius M","Niemi M"}	Clinical pharmacology and therapeutics	5	null	null	2012	22617227
The Clinical Pharmacogenetics Implementation Consortium (CPIC) guideline for SLCO1B1 and simvastatin-induced myopathy: 2014 update	100017	{"Ramsey Laura B","Johnson Samuel G","Caudle Kelly E","Haidar Cyrine E","Voora Deepak","Wilke Russell A","Maxwell Whitney D","McLeod Howard L","Krauss Ronald M","Roden Dan M","Feng Qiping","Cooper-DeHoff Rhonda M","Gong Li","Klein Teri E","Wadelius Mia","Niemi Mikko"}	Clinical pharmacology and therapeutics	6	null	null	2014	24918167
Clinical Pharmacogenetics Implementation Consortium Guideline for CYP2D6 and CYP2C19 Genotypes and Dosing of Tricyclic Antidepressants	100018	{"Hicks J K","Swen J J","Thorn C F","Sangkuhl K","Kharasch E D","Ellingrod V L","Skaar T C","Müller D J","Gaedigk A","Stingl J C"}	Clinical pharmacology and therapeutics	1	null	null	2013	23486447
Clinical Pharmacogenetics Implementation Consortium Guideline (CPIC®) for CYP2D6 and CYP2C19 Genotypes and Dosing of Tricyclic Antidepressants: 2016 Update	100018	{"Kevin Hicks J","Sangkuhl Katrin","Swen Jesse J","Ellingrod Vicki L","Müller Daniel J","Shimoda Kazutaka","Bishop Jeffrey R","Kharasch Evan D","Skaar Todd C","Gaedigk Andrea","Dunnenberger Henry M","Klein Teri E","Caudle Kelly E","Stingl Julia C"}	Clinical pharmacology and therapeutics	12	null	null	2016	27997040
Clinical Pharmacogenetics Implementation Consortium Guideline for CYP2D6 and CYP2C19 Genotypes and Dosing of Tricyclic Antidepressants	100019	{"Hicks J K","Swen J J","Thorn C F","Sangkuhl K","Kharasch E D","Ellingrod V L","Skaar T C","Müller D J","Gaedigk A","Stingl J C"}	Clinical pharmacology and therapeutics	1	null	null	2013	23486447
Clinical Pharmacogenetics Implementation Consortium Guideline (CPIC®) for CYP2D6 and CYP2C19 Genotypes and Dosing of Tricyclic Antidepressants: 2016 Update	100019	{"Kevin Hicks J","Sangkuhl Katrin","Swen Jesse J","Ellingrod Vicki L","Müller Daniel J","Shimoda Kazutaka","Bishop Jeffrey R","Kharasch Evan D","Skaar Todd C","Gaedigk Andrea","Dunnenberger Henry M","Klein Teri E","Caudle Kelly E","Stingl Julia C"}	Clinical pharmacology and therapeutics	12	null	null	2016	27997040
Clinical Pharmacogenetics Implementation Consortium (CPIC) Guidelines for HLA-B Genotype and Carbamazepine Dosing	100020	{"Leckband Susan G","Kelsoe John R","Dunnenberger H Mark","George Alfred L","Tran Eric","Berger Reisel","Müller Daniel J","Whirl-Carrillo Michelle","Caudle Kelly E","Pirmohamed Munir"}	Clinical pharmacology and therapeutics	5	null	null	2013	23695185
Clinical Pharmacogenetics Implementation Consortium Guidelines for Dihydropyrimidine Dehydrogenase Genotype and Fluoropyrimidine Dosing	100021	{"Caudle Kelly E","Thorn Caroline F","Klein Teri E","Swen Jesse J","McLeod Howard L","Diasio Robert B","Schwab Matthias"}	Clinical pharmacology and therapeutics	8	null	null	2013	23988873
Clinical Pharmacogenetics Implementation Consortium (CPIC) Guideline for Dihydropyrimidine Dehydrogenase Genotype and Fluoropyrimidine Dosing: 2017 Update	100021	{"Amstutz Ursula","Henricks Linda M","Offer Steven M","Barbarino Julia","Schellens Jan H M","Swen Jesse J","Klein Teri E","McLeod Howard L","Caudle Kelly E","Diasio Robert B","Schwab Matthias"}	Clinical pharmacology and therapeutics	11	null	null	2017	29152729
Clinical Pharmacogenetics Implementation Consortium (CPIC) Guideline for CYP2D6 Genotype and Use of Ondansetron and Tropisetron	100022	{"Bell Gillian C","Caudle Kelly E","Whirl-Carrillo Michelle","Gordon Ronald J","Hikino Keiko","Prows Cynthia A","Gaedigk Andrea","Agundez Jose A G","Sadhasivam Senthilkumar","Klein Teri E","Schwab Matthias"}	Clinical pharmacology and therapeutics	12	null	null	2016	28002639
Clinical Pharmacogenetics Implementation Consortium Guidelines for Dihydropyrimidine Dehydrogenase Genotype and Fluoropyrimidine Dosing	100023	{"Caudle Kelly E","Thorn Caroline F","Klein Teri E","Swen Jesse J","McLeod Howard L","Diasio Robert B","Schwab Matthias"}	Clinical pharmacology and therapeutics	8	null	null	2013	23988873
Clinical Pharmacogenetics Implementation Consortium Guidelines for Dihydropyrimidine Dehydrogenase Genotype and Fluoropyrimidine Dosing	100024	{"Caudle Kelly E","Thorn Caroline F","Klein Teri E","Swen Jesse J","McLeod Howard L","Diasio Robert B","Schwab Matthias"}	Clinical pharmacology and therapeutics	8	null	null	2013	23988873
Clinical Pharmacogenetics Implementation Consortium (CPIC) Guideline for Dihydropyrimidine Dehydrogenase Genotype and Fluoropyrimidine Dosing: 2017 Update	100024	{"Amstutz Ursula","Henricks Linda M","Offer Steven M","Barbarino Julia","Schellens Jan H M","Swen Jesse J","Klein Teri E","McLeod Howard L","Caudle Kelly E","Diasio Robert B","Schwab Matthias"}	Clinical pharmacology and therapeutics	11	null	null	2017	29152729
Clinical Pharmacogenetics Implementation Consortium (CPIC®) Guideline for CYP2C19 and Voriconazole Therapy	100025	{"Moriyama Brad","Obeng Aniwaa Owusu","Barbarino Julia","Penzak Scott R","Henning Stacey A","Scott Stuart A","Agúndez José A G","Wingard John R","McLeod Howard L","Klein Teri E","Cross Shane","Caudle Kelly E","Walsh Thomas J"}	Clinical pharmacology and therapeutics	12	null	null	2016	27981572
Clinical Pharmacogenetics Implementation Consortium (CPIC) Guidelines for HLA-B Genotype and Carbamazepine Dosing	100026	{"Leckband Susan G","Kelsoe John R","Dunnenberger H Mark","George Alfred L","Tran Eric","Berger Reisel","Müller Daniel J","Whirl-Carrillo Michelle","Caudle Kelly E","Pirmohamed Munir"}	Clinical pharmacology and therapeutics	5	null	null	2013	23695185
Clinical Pharmacogenetics Implementation Consortium (CPIC) Guideline for CYP2D6 Genotype and Use of Ondansetron and Tropisetron	100027	{"Bell Gillian C","Caudle Kelly E","Whirl-Carrillo Michelle","Gordon Ronald J","Hikino Keiko","Prows Cynthia A","Gaedigk Andrea","Agundez Jose A G","Sadhasivam Senthilkumar","Klein Teri E","Schwab Matthias"}	Clinical pharmacology and therapeutics	12	null	null	2016	28002639
Clinical pharmacogenetics implementation consortium (CPIC) guidelines for CYP3A5 genotype and tacrolimus dosing	100029	{"Birdwell Kelly A","Decker Brian","Barbarino Julia M","Peterson Josh F","Stein C Michael","Sadee Wolfgang","Wang Danxin","Vinks Alexander A","He Yijing","Swen Jesse J","Leeder J Steven","van Schaik R H N","Thummel Kenneth E","Klein Teri E","Caudle Kelly E","MacPhee Iain A M"}	Clinical pharmacology and therapeutics	3	null	null	2015	25801146
Clinical Pharmacogenetics Implementation Consortium (CPIC) Guideline for CYP2D6 and CYP2C19 Genotypes and Dosing of Selective Serotonin Reuptake Inhibitors	100030	{"Hicks J Kevin","Bishop Jeffrey R","Sangkuhl Katrin","Müller Daniel J","Ji Yuan","Leckband Susan G","Leeder J Steven","Graham Rebecca L","Chiulli Dana L","LLerena Adrián","Skaar Todd C","Scott Stuart A","Stingl Julia C","Klein Teri E","Caudle Kelly E","Gaedigk Andrea"}	Clinical pharmacology and therapeutics	5	null	null	2015	25974703
Clinical Pharmacogenetics Implementation Consortium (CPIC) Guideline for CYP2D6 and CYP2C19 Genotypes and Dosing of Selective Serotonin Reuptake Inhibitors	100031	{"Hicks J Kevin","Bishop Jeffrey R","Sangkuhl Katrin","Müller Daniel J","Ji Yuan","Leckband Susan G","Leeder J Steven","Graham Rebecca L","Chiulli Dana L","LLerena Adrián","Skaar Todd C","Scott Stuart A","Stingl Julia C","Klein Teri E","Caudle Kelly E","Gaedigk Andrea"}	Clinical pharmacology and therapeutics	5	null	null	2015	25974703
Clinical Pharmacogenetics Implementation Consortium (CPIC) Guideline for CYP2D6 and CYP2C19 Genotypes and Dosing of Selective Serotonin Reuptake Inhibitors	100032	{"Hicks J Kevin","Bishop Jeffrey R","Sangkuhl Katrin","Müller Daniel J","Ji Yuan","Leckband Susan G","Leeder J Steven","Graham Rebecca L","Chiulli Dana L","LLerena Adrián","Skaar Todd C","Scott Stuart A","Stingl Julia C","Klein Teri E","Caudle Kelly E","Gaedigk Andrea"}	Clinical pharmacology and therapeutics	5	null	null	2015	25974703
Clinical Pharmacogenetics Implementation Consortium (CPIC) Guideline for CYP2D6 and CYP2C19 Genotypes and Dosing of Selective Serotonin Reuptake Inhibitors	100033	{"Hicks J Kevin","Bishop Jeffrey R","Sangkuhl Katrin","Müller Daniel J","Ji Yuan","Leckband Susan G","Leeder J Steven","Graham Rebecca L","Chiulli Dana L","LLerena Adrián","Skaar Todd C","Scott Stuart A","Stingl Julia C","Klein Teri E","Caudle Kelly E","Gaedigk Andrea"}	Clinical pharmacology and therapeutics	5	null	null	2015	25974703
Clinical Pharmacogenetics Implementation Consortium (CPIC) Guideline for UGT1A1 and Atazanavir Prescribing	100034	{"Gammal Roseann S","Court Michael H","Haidar Cyrine E","Iwuchukwu Otito Frances","Gaur Aditya H","Alvarellos Maria","Guillemette Chantal","Lennox Jeffrey L","Whirl-Carrillo Michelle","Brummel Sean","Ratain Mark J","Klein Teri E","Schackman Bruce R","Caudle Kelly E","Haas David W"}	Clinical pharmacology and therapeutics	9	null	null	2015	26417955
\.

\copy publication(title,authors,journal,month,page,volume,year,pmid) from STDIN;
CPIC: Clinical Pharmacogenetics Implementation Consortium of the Pharmacogenomics Research Network	{"Relling M V","Klein T E"}	Clinical pharmacology and therapeutics	3	464-7	89	2011	21270786
Incorporation of Pharmacogenomics into Routine Clinical Practice: the Clinical Pharmacogenetics Implementation Consortium (CPIC) Guideline Development Process	{"Caudle Kelly E","Klein Teri E","Hoffman James M","Müller Daniel J","Whirl-Carrillo Michelle","Gong Li","McDonagh Ellen M","Sangkuhl Katrin","Thorn Caroline F","Schwab Matthias","Agunder Jose A G","Freimuth Robert R","Huser Vojtech","Lee Ming Ta Michael","Iwuchukwu Otito F","Crews Kristine R","Scott Stuart A","Wadelius Mia","Swen Jesse J","Tyndale Rachel F","Stein C Michael","Roden Dan","Relling Mary V","Williams Marc S","Johnson Samuel G"}	Current drug metabolism	1	null	null	2014	24479687
Standardizing terms for clinical pharmacogenetic test results: consensus terms from the Clinical Pharmacogenetics Implementation Consortium (CPIC)	{"Caudle Kelly E","Dunnenberger Henry M","Freimuth Robert R","Peterson Josh F","Burlison Jonathan D","Whirl-Carrillo Michelle","Scott Stuart A","Rehm Heidi L","Williams Marc S","Klein Teri E","Relling Mary V","Hoffman James M"}	Genetics in medicine : official journal of the American College of Medical Genetics	7	null	null	2016	27441996
\.
