name: Build project

on:
  push:
    branches:
      - "development"

env:
  POSTGRES_HOST: postgres
  POSTGRES_PASSWORD: postgres
  CPIC_HOST: postgres
  CPIC_PASS: ghtest

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    container:
      image: pgkb/base:latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Build and test
        run: ./gradlew test

      - name: Install yarn dependencies
        run: yarn install --immutable

      # checking out default branch, which should be staging!
      - name: Checkout cpic-support-files
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: cpicpgx/cpic-support-files
          path: './cpic-support-files'

      - name: Initialize dev env
        run: make db-init
